Repository travel-planner-project/TravelPlanner, pull requests merged in 2023-08, with the labels that each got.

#113 Feat: websocket group crud
  src/main/java/travelplanner/project/demo/global/exception/ExceptionType.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthService.java
  src/main/java/travelplanner/project/demo/member/Member.java
  src/main/java/travelplanner/project/demo/member/MemberRepository.java
  src/main/java/travelplanner/project/demo/member/profile/Profile.java
  src/main/java/travelplanner/project/demo/member/profile/ProfileRepository.java
  src/main/java/travelplanner/project/demo/member/profile/Service/ProfileService.java
  src/main/java/travelplanner/project/demo/member/profile/Service/UserService.java
  src/main/java/travelplanner/project/demo/planner/controller/PlannerController.java
  src/main/java/travelplanner/project/demo/planner/domain/Calendar.java
  src/main/java/travelplanner/project/demo/planner/domain/CalendarEditor.java
  src/main/java/travelplanner/project/demo/planner/domain/Date.java
  src/main/java/travelplanner/project/demo/planner/domain/Planner.java
  src/main/java/travelplanner/project/demo/planner/domain/PlannerEditor.java
  src/main/java/travelplanner/project/demo/planner/domain/ToDo.java
  src/main/java/travelplanner/project/demo/planner/domain/ToDoEditor.java
  src/main/java/travelplanner/project/demo/planner/dto/request/CalendarCreateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/CalendarDeleteRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/CalendarUpdateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/PlannerCreateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/PlannerUpdateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/ToDoCraeteRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/ToDoDeleteRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/ToDoEditRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/response/DateResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/PlannerDetailResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/PlannerListResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/ToDoResponse.java
  src/main/java/travelplanner/project/demo/planner/repository/PlannerDateRepository.java
  src/main/java/travelplanner/project/demo/planner/repository/PlannerRepository.java
  src/main/java/travelplanner/project/demo/planner/repository/ToDoRepository.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerDateService.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerService.java
  src/main/java/travelplanner/project/demo/planner/service/ToDoService.java
Labels: BugFix, BE, 임준형

#115 Test: 토큰 테스트
  .github/workflows/deploy.yml
  src/main/java/travelplanner/project/demo/global/exception/ExceptionType.java
  src/main/java/travelplanner/project/demo/global/exception/TokenExpiredException.java
  src/main/java/travelplanner/project/demo/global/security/SecurityConfig.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtController.java
  src/main/java/travelplanner/project/demo/global/util/CookieUtil.java
  src/main/java/travelplanner/project/demo/global/util/RedisUtil.java
  src/main/java/travelplanner/project/demo/global/util/TokenUtil.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthResponse.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthService.java
  src/main/java/travelplanner/project/demo/member/Member.java
  src/main/java/travelplanner/project/demo/member/MemberRepository.java
  src/main/java/travelplanner/project/demo/member/profile/Profile.java
  src/main/java/travelplanner/project/demo/member/profile/ProfileRepository.java
  src/main/java/travelplanner/project/demo/member/profile/Service/ProfileService.java
  src/main/java/travelplanner/project/demo/member/profile/Service/UserService.java
  src/main/java/travelplanner/project/demo/planner/domain/Calendar.java
  src/main/java/travelplanner/project/demo/planner/domain/CalendarEditor.java
  src/main/java/travelplanner/project/demo/planner/domain/Planner.java
  src/main/java/travelplanner/project/demo/planner/domain/ToDo.java
  src/main/java/travelplanner/project/demo/planner/dto/request/CalendarCreateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/CalendarDeleteRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/CalendarUpdateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/response/DateResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/PlannerDetailResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/PlannerListResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/ToDoResponse.java
  src/main/java/travelplanner/project/demo/planner/repository/PlannerDateRepository.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerDateService.java
Labels: BugFix, Test, BE, 김시은, Refactor

#117 Refactor: 프로필 페이지 코드 리팩토링 및 버그 수정
  client/src/hooks/useRouter.ts
  client/src/pages/Profile/DeleteUser.tsx
  client/src/pages/Profile/EditPassword.tsx
  client/src/pages/Profile/EditProfile.tsx
  client/src/pages/Profile/Profile.tsx
Labels: BugFix, FE, 최예슬, Refactor

#118 Feature: 로그인 토큰 방식 변경
  client/src/apis/instance.ts
  client/src/apis/user.ts
Labels: Feature, FE, 박설화

#119 Fix: 유저 프로필 변경 오류 수정
  .github/workflows/deploy.yml
  src/main/java/travelplanner/project/demo/global/security/SecurityConfig.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/travelplanner/project/demo/global/util/RedisUtil.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthService.java
  src/main/java/travelplanner/project/demo/member/profile/Service/ProfileService.java
  src/main/java/travelplanner/project/demo/member/profile/Service/UserService.java
Labels: BugFix, Test, BE, 김시은

#121 Test: 에러분기와 동작 테스트
  .github/workflows/deploy.yml
  src/main/java/travelplanner/project/demo/global/exception/ApiException.java
  src/main/java/travelplanner/project/demo/global/exception/ApiExceptionHandler.java
  src/main/java/travelplanner/project/demo/global/exception/ApiExceptionResponse.java
  src/main/java/travelplanner/project/demo/global/exception/ErrorType.java
  src/main/java/travelplanner/project/demo/global/exception/Exception.java
  src/main/java/travelplanner/project/demo/global/exception/ExceptionType.java
  src/main/java/travelplanner/project/demo/global/security/CustomAuthenticationProvider.java
  src/main/java/travelplanner/project/demo/global/security/CustomUserDetailsService.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtController.java
  src/main/java/travelplanner/project/demo/global/util/TokenUtil.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthController.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthService.java
  src/main/java/travelplanner/project/demo/member/profile/ProfileController.java
  src/main/java/travelplanner/project/demo/member/profile/Service/ProfileService.java
  src/main/java/travelplanner/project/demo/member/profile/Service/UserService.java
  src/main/java/travelplanner/project/demo/planner/controller/PlannerController.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerDateService.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerService.java
  src/main/java/travelplanner/project/demo/planner/service/ToDoService.java
Labels: Test, BE, 김시은, 신세인, Refactor

#124 Feat: 플래너 및 플랜 디테일 rest api 요청
  client/src/apis/instance.ts
  client/src/apis/planner.ts
  client/src/components/Common/Modal/Modal.tsx
  client/src/components/PlanDetail/PlanElement/Element.module.scss
  client/src/components/PlanDetail/PlanElement/Element.tsx
  client/src/components/Planner/AddPlanModal.tsx
  client/src/components/Planner/PlanElement.tsx
  client/src/pages/PlanDetail.tsx
  client/src/pages/Planner.tsx
  client/src/router/routerData.tsx
Labels: Feature, FE, 하종승

#128 Refac: 프로필 리팩토링
  src/main/java/travelplanner/project/demo/global/util/AuthUtil.java
  src/main/java/travelplanner/project/demo/global/util/RedisUtil.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthService.java
  src/main/java/travelplanner/project/demo/member/Member.java
  src/main/java/travelplanner/project/demo/member/profile/Profile.java
  src/main/java/travelplanner/project/demo/member/profile/ProfileController.java
  src/main/java/travelplanner/project/demo/member/profile/Service/ProfileService.java
  src/main/java/travelplanner/project/demo/member/profile/Service/UserService.java
  src/main/java/travelplanner/project/demo/member/profile/dto/request/PasswordCheckRequest.java
  src/main/java/travelplanner/project/demo/member/profile/dto/request/PasswordUpdateRequest.java
  src/main/java/travelplanner/project/demo/member/profile/dto/request/ProfileUpdateRequest.java
  src/main/java/travelplanner/project/demo/planner/domain/Calendar.java
  src/main/java/travelplanner/project/demo/planner/domain/Chatting.java
  src/main/java/travelplanner/project/demo/planner/domain/GroupMember.java
  src/main/java/travelplanner/project/demo/planner/domain/Planner.java
  src/main/java/travelplanner/project/demo/planner/domain/ToDo.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerService.java
  src/main/java/travelplanner/project/demo/planner/service/ValidatingService.java
Labels: BugFix, BE, 김시은, Refactor

#136 Fix: 프로필 버그 수정
  src/main/java/travelplanner/project/demo/member/Member.java
  src/main/java/travelplanner/project/demo/planner/domain/Planner.java
Labels: BugFix, BE, 김시은

#139 Feat: 페이징 처리와 피드 기능 구현
  src/main/java/travelplanner/project/demo/feed/controller/FeedController.java
  src/main/java/travelplanner/project/demo/feed/dto/FeedResponse.java
  src/main/java/travelplanner/project/demo/feed/service/FeedService.java
  src/main/java/travelplanner/project/demo/global/util/PageUtil.java
  src/main/java/travelplanner/project/demo/planner/domain/Planner.java
  src/main/java/travelplanner/project/demo/planner/repository/PlannerRepository.java
Labels: Feature, BE, 임준형

#127 Feat: 웹소켓 인증 로직 초안 구성
  client/src/apis/user.ts
  client/src/pages/PlanDetail.tsx
  client/src/types/planDetailTypes.ts
Labels: Feature, FE, 최예슬

#138 Feat: 바뀐 프로필 api에 맞추기
  client/src/apis/user.ts
  client/src/pages/Profile/DeleteUser.tsx
  client/src/pages/Profile/EditPassword.tsx
  client/src/pages/Profile/EditProfile.tsx
Labels: Feature, FE, 최예슬

#143 Fix: feed 와 플랜디테일 수정
  src/main/java/travelplanner/project/demo/feed/controller/FeedController.java
  src/main/java/travelplanner/project/demo/global/security/SecurityConfig.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/travelplanner/project/demo/planner/controller/CalendarController.java
  src/main/java/travelplanner/project/demo/planner/controller/ChatController.java
  src/main/java/travelplanner/project/demo/planner/controller/GroupMemberController.java
  src/main/java/travelplanner/project/demo/planner/controller/ToDoController.java
  src/main/java/travelplanner/project/demo/planner/dto/request/GroupMemberDeleteRequest.java
  src/main/java/travelplanner/project/demo/planner/service/GroupMemberService.java
Labels: BugFix, BE, 김시은

#145 Refac: Feed 공개플래너만 전체 조회로 로직 수정 (#144)
  src/main/java/travelplanner/project/demo/feed/service/FeedService.java
  src/main/java/travelplanner/project/demo/planner/repository/PlannerRepository.java
Labels: BE, 김시은, 임준형, Refactor

#140 [FE] Feat: 플래너 생성 모달에 isPrivate 선택 추가
  client/src/components/Common/Modal/Modal.module.scss
  client/src/components/Common/Modal/Modal.tsx
  client/src/components/Common/Modal/PrivacySetting.module.scss
  client/src/components/Common/Modal/PrivacySetting.tsx
Labels: Feature, FE, 박설화

#147 [FE] Feat: feed 페이지 완성
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/apis/planner.ts
  client/src/components/Common/Icon.tsx
  client/src/components/Common/Navbar/NavbarProfile.module.scss
  client/src/components/Common/Navbar/NavbarProfile.tsx
  client/src/components/Feed/PlannerTitle.module.scss
  client/src/components/Feed/PlannerTitle.tsx
  client/src/components/Feed/SearchBar.module.scss
  client/src/components/Feed/SearchBar.tsx
  client/src/hooks/useInfiniteScrolling.ts
  client/src/layout/GeneralLayout.tsx
  client/src/pages/Feed.module.scss
  client/src/pages/Feed.tsx
  client/src/pages/Planner.tsx
  client/src/router/routerData.tsx
  package-lock.json
  package.json
Labels: Feature, FE, 박설화

#150 Feat: 채팅 UI 변경
  client/src/components/PlanDetail/ChatModal/ChatModal.module.scss
  client/src/components/PlanDetail/ChatModal/ChatModal.tsx
  client/src/types/planDetailTypes.ts
Labels: Design, FE, 최예슬

#151 Feat: 웹소켓 통신을 활용한 단일 스케줄 생성
  client/src/components/PlanDetail/PlanElement/DropDown.tsx
  client/src/components/PlanDetail/PlanElement/ElementEditor.tsx
  client/src/pages/PlanDetail.tsx
  client/src/types/planDetailTypes.ts
Labels: Feature, FE, 하종승

#154 Feat: 멤버 및 프로필 수정
  .gitignore
  src/main/java/travelplanner/project/demo/feed/controller/FeedController.java
  src/main/java/travelplanner/project/demo/feed/service/FeedService.java
  src/main/java/travelplanner/project/demo/global/security/CustomAuthenticationFilter.java
  src/main/java/travelplanner/project/demo/global/security/SecurityConfig.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/travelplanner/project/demo/global/template/RestTemplateConfig.java
  src/main/java/travelplanner/project/demo/global/util/TokenUtil.java
  src/main/java/travelplanner/project/demo/member/Auth/Role.java
  src/main/java/travelplanner/project/demo/member/Member.java
  src/main/java/travelplanner/project/demo/member/MemberEditor.java
  src/main/java/travelplanner/project/demo/member/auth/AuthController.java
  src/main/java/travelplanner/project/demo/member/auth/AuthResponse.java
  src/main/java/travelplanner/project/demo/member/auth/AuthService.java
  src/main/java/travelplanner/project/demo/member/auth/LoginRequest.java
  src/main/java/travelplanner/project/demo/member/auth/RegisterRequest.java
  src/main/java/travelplanner/project/demo/member/auth/Role.java
  src/main/java/travelplanner/project/demo/member/profile/Profile.java
  src/main/java/travelplanner/project/demo/member/profile/ProfileEditor.java
  src/main/java/travelplanner/project/demo/member/profile/Service/ProfileService.java
  src/main/java/travelplanner/project/demo/member/profile/Service/UserService.java
  src/main/java/travelplanner/project/demo/member/profile/dto/response/ProfileResponse.java
  src/main/java/travelplanner/project/demo/member/profile/dto/response/ProfileUpdateResponse.java
  src/main/java/travelplanner/project/demo/member/socialauth/ClientConfig.java
  src/main/java/travelplanner/project/demo/member/socialauth/NaverLoginController.java
  src/main/java/travelplanner/project/demo/member/socialauth/OAuth2UserInfo.java
  src/main/java/travelplanner/project/demo/member/socialauth/Oauth2AuthenticationSuccessHandler.java
  src/main/java/travelplanner/project/demo/member/socialauth/PrincipalDetails.java
  src/main/java/travelplanner/project/demo/member/socialauth/PrincipalOauth2UserService.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOAuth.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOAuthService.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOAuthTokenRequest.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOAuthTokenResponse.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOauthController.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleUserInfoDto.java
  src/main/java/travelplanner/project/demo/member/socialauth/kakao/KakaoUserInfo.java
  src/main/java/travelplanner/project/demo/planner/repository/PlannerRepository.java
  src/main/java/travelplanner/project/demo/planner/service/ValidatingService.java
  src/main/resources/application.yml
Labels: BE, 신세인, Refactor

#159 Feat: plannerresponse chattingLIst 및 groupMemberList 추가
  src/main/java/travelplanner/project/demo/planner/domain/Chatting.java
  src/main/java/travelplanner/project/demo/planner/domain/GroupMember.java
  src/main/java/travelplanner/project/demo/planner/domain/Planner.java
  src/main/java/travelplanner/project/demo/planner/dto/response/ChatResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/GroupMemberResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/PlannerCreateResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/PlannerDetailResponse.java
  src/main/java/travelplanner/project/demo/planner/repository/ChattingRepository.java
  src/main/java/travelplanner/project/demo/planner/repository/GroupMemberRepository.java
  src/main/java/travelplanner/project/demo/planner/service/ChatService.java
  src/main/java/travelplanner/project/demo/planner/service/GroupMemberService.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerService.java
Labels: Feature, BE, 신세인, 임준형, Refactor

#158 [FE] Fix: date fns 라이브러리 재설치 및 자잘한 수정
  client/package-lock.json
  client/package.json
  client/src/hooks/useLogout.ts
  client/src/router/routerData.tsx
  client/src/utils/tokenHandler.ts
  package-lock.json
  package.json
Labels: BugFix, FE, 박설화

#161 Feat: 웹소켓 통신을 활용한 스케줄 수정
  client/src/components/Common/Modal/InviteModal.tsx
  client/src/components/Common/Modal/Modal.tsx
  client/src/components/PlanDetail/PlanElement/Element.tsx
  client/src/components/PlanDetail/PlanElement/ElementEditor.tsx
  client/src/hooks/useModal.ts
  client/src/pages/PlanDetail.module.scss
  client/src/pages/PlanDetail.tsx
  client/src/pages/Planner.tsx
  client/src/router/routerData.tsx
  client/src/store/store.ts
  client/src/types/planDetailTypes.ts
  client/src/utils/date.ts
Labels: Feature, FE, 하종승

#166 Feat: 플랜 디테일 권한별 응답 클래스 구별
  src/main/java/travelplanner/project/demo/global/util/AuthUtil.java
  src/main/java/travelplanner/project/demo/planner/controller/PlannerController.java
  src/main/java/travelplanner/project/demo/planner/dto/response/plannerdetail/PlannerDetailAuthorizedResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/plannerdetail/PlannerDetailResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/plannerdetail/PlannerDetailUnauthorizedResponse.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerService.java
Labels: Feature, BE, 임준형, Refactor

#172 Feat: 리프레시토큰 만료기한 설정과 갱신
  src/main/java/travelplanner/project/demo/global/exception/ErrorType.java
  src/main/java/travelplanner/project/demo/global/security/CustomAuthenticationEntryPoint.java
  src/main/java/travelplanner/project/demo/global/security/CustomAuthenticationFilter.java
  src/main/java/travelplanner/project/demo/global/security/CustomAuthenticationProvider.java
  src/main/java/travelplanner/project/demo/global/security/CustomUserDetailsService.java
  src/main/java/travelplanner/project/demo/global/security/SecurityConfig.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtController.java
  src/main/java/travelplanner/project/demo/global/util/AuthUtil.java
  src/main/java/travelplanner/project/demo/global/util/CookieUtil.java
  src/main/java/travelplanner/project/demo/global/util/RedisUtil.java
  src/main/java/travelplanner/project/demo/global/util/TokenUtil.java
  src/main/java/travelplanner/project/demo/member/auth/AuthController.java
  src/main/java/travelplanner/project/demo/member/auth/AuthService.java
  src/main/java/travelplanner/project/demo/planner/controller/GroupMemberController.java
Labels: Feature, BE, 김시은

#174 Fix: Host가 아닌 Member일경우 플래너가 안보이는 오류 수정 (#173)
  src/main/java/travelplanner/project/demo/planner/service/PlannerService.java
Labels: BE, BREAKING CHANGE, 임준형

#176 Refac: dto setter 전부 제거
  src/main/java/travelplanner/project/demo/member/auth/LoginRequest.java
  src/main/java/travelplanner/project/demo/member/auth/RegisterRequest.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOAuthService.java
  src/main/java/travelplanner/project/demo/planner/dto/request/CalendarCreateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/CalendarDeleteRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/CalendarEditRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/ChatRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/GroupMemberCreateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/GroupMemberDeleteRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/GroupMemberSearchRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/PlannerCreateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/PlannerDeleteRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/PlannerEditRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/response/GroupMemberSearchResponse.java
  src/main/java/travelplanner/project/demo/planner/service/GroupMemberService.java
Labels: BE, 임준형, Refactor

#168 [FE] Feat: refresh token 만료되었을 때 로그아웃 기능
  client/src/apis/instance.ts
  client/src/pages/SignIn.tsx
Labels: Feature, FE, 박설화
