Repository travel-planner-project/TravelPlanner, pull requests merged in 2023-09, with the labels that each got.

#179 Feat: 웹소켓 에러 핸들러 작성 및 에러 분기 처리
  src/main/java/travelplanner/project/demo/global/config/WebSocketConfig.java
  src/main/java/travelplanner/project/demo/global/exception/ErrorType.java
  src/main/java/travelplanner/project/demo/global/exception/WebSocket/WebSocketErrorController.java
  src/main/java/travelplanner/project/demo/global/handler/StompErrorHandler.java
  src/main/java/travelplanner/project/demo/global/handler/StompHandler.java
  src/main/java/travelplanner/project/demo/global/util/WebsocketUtil.java
  src/main/java/travelplanner/project/demo/planner/controller/ChatController.java
  src/main/java/travelplanner/project/demo/planner/service/ChatService.java
  src/main/java/travelplanner/project/demo/planner/service/GroupMemberService.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerService.java
  src/main/java/travelplanner/project/demo/planner/service/ToDoService.java
  src/main/java/travelplanner/project/demo/planner/service/ValidatingService.java
Labels: Feature, BE, 신세인, Refactor

#170 [FE] Feat: 이전 채팅 내용 저장
  client/src/components/PlanDetail/ChatModal/ChatModal.tsx
  client/src/pages/PlanDetail.tsx
  client/src/types/planDetailTypes.ts
Labels: Feature, FE, 최예슬

#184 [FE] Fix: planPeriodBox 소문자를 대문자로 수정 (#183)
  client/src/components/PlanDetail/PlanPeriodBox.tsx
Labels: BugFix, FE, 하종승

#185 Feat: 소셜 로그인 기능 구현
  .gradle/8.1.1/checksums/checksums.lock
  .gradle/8.1.1/checksums/md5-checksums.bin
  .gradle/8.1.1/checksums/sha1-checksums.bin
  src/main/java/travelplanner/project/demo/feed/controller/FeedController.java
  src/main/java/travelplanner/project/demo/feed/service/FeedService.java
  src/main/java/travelplanner/project/demo/global/security/CustomAuthenticationEntryPoint.java
  src/main/java/travelplanner/project/demo/global/security/SecurityConfig.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtController.java
  src/main/java/travelplanner/project/demo/global/security/jwt/TokenExpiredException.java
  src/main/java/travelplanner/project/demo/global/template/RestTemplateConfig.java
  src/main/java/travelplanner/project/demo/global/util/TokenUtil.java
  src/main/java/travelplanner/project/demo/member/MemberRepository.java
  src/main/java/travelplanner/project/demo/member/socialauth/ClientConfig.java
  src/main/java/travelplanner/project/demo/member/socialauth/CustomOAuth2UserService.java
  src/main/java/travelplanner/project/demo/member/socialauth/NaverLoginController.java
  src/main/java/travelplanner/project/demo/member/socialauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/travelplanner/project/demo/member/socialauth/OAuth2UserInfo.java
  src/main/java/travelplanner/project/demo/member/socialauth/OAuthUserInfoFactory.java
  src/main/java/travelplanner/project/demo/member/socialauth/Oauth2AuthenticationSuccessHandler.java
  src/main/java/travelplanner/project/demo/member/socialauth/PrincipalDetails.java
  src/main/java/travelplanner/project/demo/member/socialauth/PrincipalOauth2UserService.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOAuth.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOAuthService.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOAuthTokenRequest.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOAuthTokenResponse.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleOauthController.java
  src/main/java/travelplanner/project/demo/member/socialauth/google/GoogleUserInfoDto.java
  src/main/java/travelplanner/project/demo/member/socialauth/userInfo/GoogleUserInfo.java
  src/main/java/travelplanner/project/demo/member/socialauth/userInfo/KakaoUserInfo.java
  src/main/java/travelplanner/project/demo/member/socialauth/userInfo/NaverUserInfo.java
  src/main/java/travelplanner/project/demo/planner/controller/ChatController.java
  src/main/java/travelplanner/project/demo/planner/controller/GroupMemberController.java
  src/main/java/travelplanner/project/demo/planner/dto/request/GroupMemberCreateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/GroupMemberDeleteRequest.java
  src/main/java/travelplanner/project/demo/planner/service/ToDoService.java
  src/main/resources/templates/firebase-snippet.html
Labels: Feature, BE, 김시은, 신세인, 임준형

#189 fix: 프로필 이미지 변경 프리뷰가 원에 꽉 차도록 고침 (#188)
  client/src/pages/Profile/EditProfile.module.scss
  client/src/pages/Profile/EditProfile.tsx
Labels: BugFix, FE, 박설화

#192 fix: 친구 초대 모달의 유저 검색 시 프로필 이미지 뜨도록 고침
  client/src/components/Common/Modal/FriendInfo.tsx
Labels: BugFix, FE, 박설화

#194 feat: 친구 검색 실패 message 보여주는 alert 추가
  client/src/components/Common/Modal/FriendInfo.tsx
  client/src/components/Common/Modal/InviteModal.tsx
Labels: Feature, FE, 박설화

#196 fix: 그룹 멤버 추가 성공시 오는 웹소켓 응답을 groupMember 에 추가
  client/src/pages/PlanDetail.tsx
Labels: BugFix, FE, 박설화

#198 Feat: 플래너 스크롤 기능
  client/src/pages/PlanDetail.module.scss
Labels: Feature, FE, 하종승

#207 [BE] Feat: 포스트 댓글 기능
  src/main/java/travelplanner/project/demo/domain/comment/controller/CommentController.java
  src/main/java/travelplanner/project/demo/domain/comment/domain/Comment.java
  src/main/java/travelplanner/project/demo/domain/comment/domain/CommentEditor.java
  src/main/java/travelplanner/project/demo/domain/comment/dto/request/CommentCreateRequest.java
  src/main/java/travelplanner/project/demo/domain/comment/dto/request/CommentEditRequest.java
  src/main/java/travelplanner/project/demo/domain/comment/dto/response/CommentResponse.java
  src/main/java/travelplanner/project/demo/domain/comment/repository/CommentRepository.java
  src/main/java/travelplanner/project/demo/domain/comment/service/CommentService.java
  src/main/java/travelplanner/project/demo/domain/feed/service/FeedService.java
  src/main/java/travelplanner/project/demo/domain/member/domain/Member.java
  src/main/java/travelplanner/project/demo/domain/planner/groupmember/controller/GroupMemberController.java
  src/main/java/travelplanner/project/demo/domain/planner/groupmember/dto/response/GroupMemberDeleteResponse.java
  src/main/java/travelplanner/project/demo/domain/planner/groupmember/service/GroupMemberService.java
  src/main/java/travelplanner/project/demo/domain/post/image/domain/Image.java
  src/main/java/travelplanner/project/demo/domain/post/image/dto/response/ImageResponse.java
  src/main/java/travelplanner/project/demo/domain/post/image/repository/ImageRepository.java
  src/main/java/travelplanner/project/demo/domain/post/post/controller/PostController.java
  src/main/java/travelplanner/project/demo/domain/post/post/domain/Post.java
  src/main/java/travelplanner/project/demo/domain/post/post/dto/request/PostCreateRequest.java
  src/main/java/travelplanner/project/demo/domain/post/post/dto/request/PostDeleteRequest.java
  src/main/java/travelplanner/project/demo/domain/post/post/dto/request/PostUpdateRequest.java
  src/main/java/travelplanner/project/demo/domain/post/post/dto/response/PostDetailResponse.java
  src/main/java/travelplanner/project/demo/domain/post/post/dto/response/PostListResponse.java
  src/main/java/travelplanner/project/demo/domain/post/post/repository/PostRepository.java
  src/main/java/travelplanner/project/demo/domain/post/post/service/PostService.java
  src/main/java/travelplanner/project/demo/domain/profile/Service/ProfileService.java
  src/main/java/travelplanner/project/demo/domain/profile/Service/UserService.java
  src/main/java/travelplanner/project/demo/global/exception/ErrorType.java
  src/main/java/travelplanner/project/demo/global/util/PageUtil.java
  src/main/java/travelplanner/project/demo/global/util/S3Util.java
Labels: Feature, Test, BE, 신세인, 임준형, Refactor
