Repository travel-planner-project/TravelPlanner, pull requests merged in 2023-07, with the labels that each got.

#11 Chore: 개발환경 셋팅 (#10)
  client/package-lock.json
  client/package.json
  client/src/App.tsx
Labels: Setting, FE, 박설화, 하종승, 최예슬

#14 Chore: 폴더 구조 및 라이브러리 설치 (#13)
  client/package-lock.json
  client/package.json
  client/src/apis/.gitkeep
  client/src/components/Chatting/.gitkeep
  client/src/components/Home/.gitkeep
  client/src/components/Planner/.gitkeep
  client/src/components/SignIn/.gitkeep
  client/src/components/SignUp/.gitkeep
  client/src/pages/Chatting.tsx
  client/src/pages/Home.tsx
  client/src/pages/Planner.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/router/.gitkeep
  client/src/store/.gitkeep
Labels: Setting, FE, 박설화

#21 Chore: 전역 스타일 설정 (#20)
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/styles/_color.scss
  client/src/styles/_reset.scss
  client/src/styles/_typography.scss
  client/src/styles/_utils.scss
  client/src/styles/global.scss
Labels: Setting, FE, 박설화, 하종승, 최예슬

#28 Feat: Sprite SVG 로 Icon 컴포넌츠구현
  client/.eslintrc.cjs
  client/src/App.tsx
  client/src/assets/sprite-icon.svg
  client/src/components/common/Icon.tsx
  client/src/styles/global.scss
Labels: Feature, Design, FE, 박설화

#23 Feat: NavBar 완성
  client/src/App.tsx
  client/src/components/Common/Navbar.module.scss
  client/src/components/Common/Navbar.tsx
  client/src/components/Common/NavbarProfile.module.scss
  client/src/components/Common/NavbarProfile.tsx
  client/src/components/Profile/.gitkeep
  client/src/layout/GeneralLayout.module.scss
  client/src/layout/GeneralLayout.tsx
  client/src/pages/Profile.tsx
  client/src/router/routerData.tsx
  client/src/styles/_typography.scss
  package-lock.json
  package.json
Labels: Feature, FE, 박설화

#30 [FE] Design: Planner 컴포넌트 레이아웃
  client/src/pages/Planner.module.scss
  client/src/pages/Planner.tsx
  client/src/styles/_typography.scss
Labels: Design, FE, 하종승

#33 Fix: navbar 비율 조정 프로필 이미지 가운데 정렬
  client/src/components/Common/Navbar.module.scss
  client/src/components/Common/NavbarProfile.module.scss
  client/src/components/Common/NavbarProfile.tsx
  client/src/components/common/Icon.tsx
  client/src/layout/GeneralLayout.module.scss
Labels: BugFix, FE, 박설화

#34 Design: chatting 기본 레이아웃 구성
  client/src/components/Chatting/.gitkeep
  client/src/components/Planner/.gitkeep
  client/src/components/Planner/Chatting.module.scss
  client/src/components/Planner/Chatting.tsx
  client/src/components/common/Icon.tsx
  client/src/pages/Chatting.tsx
  client/src/styles/_typography.scss
Labels: Design, FE, 최예슬

#37 Design: 스포카한산스네오 폰트 설치 및 적용 (#36)
  client/src/styles/fonts/SpoqaHanSansNeo-Bold.woff2
  client/src/styles/fonts/SpoqaHanSansNeo-Light.woff2
  client/src/styles/fonts/SpoqaHanSansNeo-Medium.woff2
  client/src/styles/fonts/SpoqaHanSansNeo-Regular.woff2
  client/src/styles/fonts/SpoqaHanSansNeo-Thin.woff2
  client/src/styles/fonts/font.scss
  client/src/styles/global.scss
Labels: Design, FE, 박설화

#38 Feat: 로그인 회원가입 UI
  client/.eslintrc.cjs
  client/src/assets/sprite-icon.svg
  client/src/components/SignIn/Email.tsx
  client/src/components/SignIn/Label.module.scss
  client/src/components/SignIn/Password.tsx
  client/src/components/SignUp/Email.tsx
  client/src/components/SignUp/Form.module.scss
  client/src/components/SignUp/Nickname.tsx
  client/src/components/SignUp/Password.tsx
  client/src/components/SignUp/PasswordCheck.tsx
  client/src/components/SignUp/ShowPasswordButton.module.scss
  client/src/components/SignUp/ShowPasswordButton.tsx
  client/src/components/common/Icon.tsx
  client/src/pages/SignIn.module.scss
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.module.scss
  client/src/pages/SignUp.tsx
  client/src/router/routerData.tsx
  client/src/styles/_color.scss
  client/src/styles/_typography.scss
  client/src/types/SignUp.ts
Labels: Feature, FE, 박설화

#45 [FE] Feat: Planner 컴포넌트
  client/src/assets/sprite-icon.svg
  client/src/components/Common/NavbarProfile.tsx
  client/src/components/PlanDetail/PlanElement/Element.module.scss
  client/src/components/PlanDetail/PlanElement/Element.tsx
  client/src/components/PlanDetail/PlanElement/Tapbar.module.scss
  client/src/components/PlanDetail/PlanElement/Tapbar.tsx
  client/src/components/common/Icon.tsx
  client/src/pages/PlanDetail.module.scss
  client/src/pages/PlanDetail.tsx
  client/src/pages/Planner.module.scss
  client/src/pages/Planner.tsx
  client/src/router/routerData.tsx
Labels: Feature, FE, 하종승

#46 Feat: checklist UI 구현
  client/src/assets/sprite-icon.svg
  client/src/components/PlanDetail/PlanElement/Checklist/Checklist.module.scss
  client/src/components/PlanDetail/PlanElement/Checklist/Checklist.tsx
  client/src/components/PlanDetail/PlanElement/Checklist/ListItem.module.scss
  client/src/components/PlanDetail/PlanElement/Checklist/ListItem.tsx
  client/src/components/common/Icon.tsx
  client/src/styles/_typography.scss
Labels: Feature, FE, 박설화

#52 Feat: chatting 모달 plandetail 페이지에 연결
  client/src/components/PlanDetail/ChatModal/ChatModal.module.scss
  client/src/components/PlanDetail/ChatModal/ChatModal.tsx
  client/src/components/Planner/Chatting.tsx
  client/src/components/SignUp/Email.tsx
  client/src/components/SignUp/Nickname.tsx
  client/src/components/SignUp/Password.tsx
  client/src/components/SignUp/PasswordCheck.tsx
  client/src/pages/PlanDetail.module.scss
  client/src/pages/PlanDetail.tsx
  client/src/pages/SignUp.tsx
  client/src/types/planDetailTypes.ts
  client/src/types/signUpTypes.ts
Labels: Feature, FE, 박설화, 하종승, 최예슬

#53 [FE] Feat: Planner 데이터 맵핑
  client/src/apis/planner.ts
  client/src/assets/sprite-icon.svg
  client/src/components/Common/Navbar.tsx
  client/src/components/Planner/AddPlanModal.module.scss
  client/src/components/Planner/AddPlanModal.tsx
  client/src/components/Planner/PlanElement.module.scss
  client/src/components/Planner/PlanElement.tsx
  client/src/pages/PlanDetail.module.scss
  client/src/pages/PlanDetail.tsx
  client/src/pages/Planner.module.scss
  client/src/pages/Planner.tsx
Labels: Feature, FE, 하종승

#55 Fix: built 에러 해결을 위해 사용하지 않는 변수 삭제 (#54)
  client/src/App.tsx
  client/src/components/Common/Icon.tsx
  client/src/components/PlanDetail/PlanElement/Tapbar.tsx
  client/src/layout/GeneralLayout.tsx
  client/src/pages/Planner.tsx
Labels: BugFix, FE, 박설화

#56 Revert "Fix: built 에러 해결을 위해 사용하지 않는 변수 삭제 (#54)"
  client/src/App.tsx
  client/src/components/Common/Icon.tsx
  client/src/components/PlanDetail/PlanElement/Tapbar.tsx
  client/src/layout/GeneralLayout.tsx
  client/src/pages/Planner.tsx
Labels: BugFix, FE, 박설화

#66 Chore: vercel.json 에 rewrites 추가 (#63)
  client/vercel.json
Labels: Deploy, FE, 박설화

#71 Chore: 프로젝트 기본 설정 (#67)
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/global/config/SwaggerConfig.java
  server/src/main/java/global/config/WebSocketConfig.java
  server/src/main/java/travelplanner/server/demo/DemoApplication.java
  server/src/main/resources/application.yml
  server/src/test/java/travelplanner/server/demo/DemoApplicationTests.java
Labels: Setting, BE, 김시은

#78 Feat: 유저 기능 추가
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/travelplanner/project/demo/global/config/SpringDocsConfig.java
  src/main/java/travelplanner/project/demo/global/exception/ApiException.java
  src/main/java/travelplanner/project/demo/global/exception/ApiExceptionHandler.java
  src/main/java/travelplanner/project/demo/global/exception/Exception.java
  src/main/java/travelplanner/project/demo/global/exception/ExceptionType.java
  src/main/java/travelplanner/project/demo/global/security/AuthConfig.java
  src/main/java/travelplanner/project/demo/global/security/SecurityConfig.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtService.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthController.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthResponse.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthService.java
  src/main/java/travelplanner/project/demo/member/Auth/LoginRequest.java
  src/main/java/travelplanner/project/demo/member/Auth/RegisterRequest.java
  src/main/java/travelplanner/project/demo/member/Auth/Role.java
  src/main/java/travelplanner/project/demo/member/Member.java
  src/main/java/travelplanner/project/demo/member/MemberRepository.java
  src/main/resources/application.yml
Labels: Feature, BE, 김시은

#82 Feat: 회원가입 로그인 서버와 연결
  client/.eslintrc.cjs
  client/src/App.tsx
  client/src/apis/instance.ts
  client/src/apis/user.ts
  client/src/components/Common/LogoutBtn.module.scss
  client/src/components/Common/LogoutBtn.tsx
  client/src/components/Common/Navbar.module.scss
  client/src/components/Common/Navbar.tsx
  client/src/components/SignUp/Nickname.tsx
  client/src/hooks/useRouter.ts
  client/src/layout/GeneralLayout.tsx
  client/src/main.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/store/store.ts
  client/src/types/signUpTypes.ts
  client/src/utils/tokenHandler.ts
  client/tsconfig.eslint.json
  client/vite.config.ts
Labels: Feature, FE, 박설화

#86 Fix: 회원 가입 로그인 부분 수정
  src/main/java/travelplanner/project/demo/global/exception/ApiException.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthController.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthResponse.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthService.java
  src/main/resources/application.yml
Labels: BugFix, BE, 김시은

#88 Design: 프로필 페이지 UI 구현
  client/src/assets/sprite-icon.svg
  client/src/components/Common/Icon.tsx
  client/src/components/Profile/RenderCheck.module.scss
  client/src/components/Profile/RenderCheck.tsx
  client/src/components/Profile/RenderEdit.module.scss
  client/src/components/Profile/RenderEdit.tsx
  client/src/components/Profile/RenderSuccess.tsx
  client/src/pages/Profile.tsx
  client/src/pages/Profile/DeleteUser.module.scss
  client/src/pages/Profile/DeleteUser.tsx
  client/src/pages/Profile/EditPassword.tsx
  client/src/pages/Profile/EditProfile.module.scss
  client/src/pages/Profile/EditProfile.tsx
  client/src/pages/Profile/Profile.module.scss
  client/src/pages/Profile/Profile.tsx
  client/src/router/routerData.tsx
Labels: Design, FE, 최예슬

#94 Fix: 프로필 민감정보 예외처리 관련 오류 해결
  .gitignore
  src/main/java/travelplanner/project/demo/global/exception/ExceptionType.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthController.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthResponse.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthService.java
  src/main/java/travelplanner/project/demo/member/profile/Profile.java
  src/main/java/travelplanner/project/demo/member/profile/ProfileController.java
  src/main/java/travelplanner/project/demo/member/profile/Service/ProfileService.java
  src/main/java/travelplanner/project/demo/member/profile/Service/UserService.java
  src/main/java/travelplanner/project/demo/member/profile/dto/request/ProfileUpdateRequest.java
  src/main/resources/application.yml
Labels: BugFix, BE, 김시은

#91 Feat: 로그인 response 로 오는 user info 저장
  client/src/components/Common/Navbar.tsx
  client/src/components/Common/NavbarProfile.tsx
  client/src/pages/SignIn.tsx
  client/src/store/store.ts
Labels: Feature, FE, 박설화

#93 Refactor: Password, PasswordCheck 컴포넌트 리팩토링 (#92)
  client/src/components/Profile/RenderEdit.tsx
  client/src/components/SignUp/Password.tsx
  client/src/components/SignUp/PasswordCheck.tsx
  client/src/types/signUpTypes.ts
Labels: FE, 박설화, Refactor

#96 Feat: useLogout 커스텀 훅 완성 (#95)
  client/src/components/Common/LogoutBtn.tsx
  client/src/hooks/useLogout.ts
Labels: Feature, FE, 박설화

#100 Feat: 친구 추가용 친구 찾기 모달 UI
  client/src/components/Common/Modal/FriendInfo.module.scss
  client/src/components/Common/Modal/FriendInfo.tsx
  client/src/components/Common/Modal/InviteModal.tsx
  client/src/components/Common/Modal/Modal.module.scss
  client/src/components/Common/Modal/Modal.tsx
  client/src/components/Common/Navbar/LogoutBtn.module.scss
  client/src/components/Common/Navbar/LogoutBtn.tsx
  client/src/components/Common/Navbar/Navbar.module.scss
  client/src/components/Common/Navbar/Navbar.tsx
  client/src/components/Common/Navbar/NavbarProfile.module.scss
  client/src/components/Common/Navbar/NavbarProfile.tsx
  client/src/hooks/useModal.ts
  client/src/layout/GeneralLayout.tsx
  client/src/store/store.ts
Labels: Feature, FE, 박설화

#101 Feat: 프로필 페이지 api 연결
  client/src/apis/instance.ts
  client/src/apis/user.ts
  client/src/components/Common/Navbar/NavbarProfile.tsx
  client/src/components/Profile/RenderCheck.tsx
  client/src/components/Profile/RenderEdit.tsx
  client/src/components/Profile/RenderSuccess.tsx
  client/src/pages/Profile/DeleteUser.tsx
  client/src/pages/Profile/EditPassword.tsx
  client/src/pages/Profile/EditProfile.module.scss
  client/src/pages/Profile/EditProfile.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/router/routerData.tsx
Labels: Feature, FE, 최예슬

#102 Feat: 플랜 디테일 더미 데이터 맵핑 테스트
  client/src/components/PlanDetail/PlanElement/Element.tsx
  client/src/pages/PlanDetail.module.scss
  client/src/pages/PlanDetail.tsx
  client/src/pages/Planner.tsx
  client/src/types/planDetailTypes.ts
Labels: Feature, Test, FE, 하종승

#104 99 be fix 프로필 화면과 서버 연동하는 부분에서 생기는 오류 해결
  .github/workflows/deploy.yml
  src/main/java/travelplanner/project/demo/member/Auth/AuthService.java
  src/main/java/travelplanner/project/demo/member/profile/ProfileController.java
  src/main/java/travelplanner/project/demo/member/profile/Service/ProfileService.java
  src/main/java/travelplanner/project/demo/member/profile/dto/request/ProfileUpdateRequest.java
  src/main/java/travelplanner/project/demo/member/profile/dto/response/ProfileUpdateResponse.java
Labels: BugFix, BE, 김시은

#107 Refac: 유저 기능 로직 변경
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/travelplanner/project/demo/global/config/RedisConfig.java
  src/main/java/travelplanner/project/demo/global/exception/ExceptionType.java
  src/main/java/travelplanner/project/demo/global/security/AuthConfig.java
  src/main/java/travelplanner/project/demo/global/security/CustomAuthenticationFilter.java
  src/main/java/travelplanner/project/demo/global/security/CustomAuthenticationProvider.java
  src/main/java/travelplanner/project/demo/global/security/CustomUserDetails.java
  src/main/java/travelplanner/project/demo/global/security/CustomUserDetailsService.java
  src/main/java/travelplanner/project/demo/global/security/SecurityConfig.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtController.java
  src/main/java/travelplanner/project/demo/global/security/jwt/JwtService.java
  src/main/java/travelplanner/project/demo/global/util/CookieUtil.java
  src/main/java/travelplanner/project/demo/global/util/RedisUtil.java
  src/main/java/travelplanner/project/demo/global/util/TokenUtil.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthController.java
  src/main/java/travelplanner/project/demo/member/Auth/AuthService.java
  src/main/java/travelplanner/project/demo/member/Member.java
  src/main/java/travelplanner/project/demo/member/MemberRepository.java
  src/main/java/travelplanner/project/demo/member/MemberService.java
  src/main/java/travelplanner/project/demo/member/profile/ProfileController.java
  src/main/java/travelplanner/project/demo/member/profile/Service/ProfileService.java
  src/main/java/travelplanner/project/demo/member/profile/Service/UserService.java
  src/main/java/travelplanner/project/demo/member/profile/dto/request/ProfileUpdateRequest.java
  src/main/java/travelplanner/project/demo/member/profile/dto/response/ProfileUpdateResponse.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerService.java
  src/main/resources/application.yml
Labels: BugFix, BE, 김시은, Refactor

#111 Feat: todo crud group crud search
  src/main/java/travelplanner/project/demo/global/exception/ExceptionType.java
  src/main/java/travelplanner/project/demo/planner/controller/PlannerController.java
  src/main/java/travelplanner/project/demo/planner/domain/Date.java
  src/main/java/travelplanner/project/demo/planner/domain/Planner.java
  src/main/java/travelplanner/project/demo/planner/domain/PlannerDate.java
  src/main/java/travelplanner/project/demo/planner/domain/PlannerDateEditor.java
  src/main/java/travelplanner/project/demo/planner/domain/PlannerEditor.java
  src/main/java/travelplanner/project/demo/planner/domain/ToDo.java
  src/main/java/travelplanner/project/demo/planner/domain/ToDoEditor.java
  src/main/java/travelplanner/project/demo/planner/dto/request/DateCreateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/DateUpdateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/PlannerCreateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/PlannerUpdateRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/ToDoCraeteRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/ToDoDeleteRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/request/ToDoEditRequest.java
  src/main/java/travelplanner/project/demo/planner/dto/response/DateResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/PlannerDetailResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/PlannerListResponse.java
  src/main/java/travelplanner/project/demo/planner/dto/response/ToDoResponse.java
  src/main/java/travelplanner/project/demo/planner/repository/PlannerDateRepository.java
  src/main/java/travelplanner/project/demo/planner/repository/PlannerRepository.java
  src/main/java/travelplanner/project/demo/planner/repository/ToDoRepository.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerDateService.java
  src/main/java/travelplanner/project/demo/planner/service/PlannerService.java
  src/main/java/travelplanner/project/demo/planner/service/ToDoService.java
Labels: Feature, BE, 임준형
